In [1]:
import google.datalab.bigquery as bq
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# apm_os 20180129 28일 15~ 19시

In [1]:
%%bq query 
--name ora_data1
SELECT stat_id, COUNT(time)
FROM(
  SELECT *, UNIX_SECONDS(time) as unixtime
  FROM `xmdw31.ods_mga.ora_db_stat_temp_20180129` AS wp_29
)
WHERE unixtime>1517151600 and unixtime<=1517166000 and sigma_value <> 0
GROUP BY stat_id
ORDER BY stat_id

QueryResultsTable job_K-PI7EkHj2WFOi-xAZIaRapAslwU

In [11]:
%%bq query --name ora_D28_15to19
SELECT time, stat_id, sigma_value
FROM(
  SELECT *, UNIX_SECONDS(time) as unixtime
  FROM `xmdw31.ods_mga.ora_db_stat_temp_20180129` AS os_29
)
WHERE unixtime>1517151600 and unixtime<=1517166000 and (stat_id = 6 or stat_id = 7 or stat_id = 8 or stat_id = 19 or stat_id = 20 or stat_id = 22 or stat_id = 26 or stat_id = 55 or stat_id = 63 or stat_id = 84 or stat_id = 93 or stat_id = 100 or stat_id = 194 or stat_id = 231 or stat_id = 623 or stat_id = 629 or stat_id = 679)
ORDER BY time, stat_id

In [8]:
%%bq query 
--name ora_D28_15to19
SELECT time, stat_id, sigma_value
FROM(
  SELECT *, UNIX_SECONDS(time) as unixtime
  FROM `xmdw31.ods_mga.ora_db_stat_temp_20180129` AS os_29
)
WHERE unixtime>1517151600 and unixtime<=1517166000 and (stat_id = 6 or stat_id = 7 or stat_id = 8 or stat_id = 19 or stat_id = 20 or stat_id = 22 or stat_id = 26 or stat_id = 55 or stat_id = 63 or stat_id = 84 or stat_id = 93 or stat_id = 100 or stat_id = 194 or stat_id = 231 or stat_id = 623 or stat_id = 629 or stat_id = 679)
ORDER BY time, stat_id

QueryResultsTable job_Wy9tK7wkAecHFML2yj8L-XPXnpjI

In [12]:
ora_D28_15to19_sql = 'SELECT time, stat_id, sigma_value FROM( SELECT *, UNIX_SECONDS(time) as unixtime FROM `xmdw31.ods_mga.ora_db_stat_temp_20180129` AS os_29 ) WHERE unixtime>1517151600 and unixtime<=1517166000 and (stat_id = 6 or stat_id = 7 or stat_id = 8 or stat_id = 19 or stat_id = 20 or stat_id = 22 or stat_id = 26 or stat_id = 55 or stat_id = 63 or stat_id = 84 or stat_id = 93 or stat_id = 100 or stat_id = 194 or stat_id = 231 or stat_id = 623 or stat_id = 629 or stat_id = 679) ORDER BY time, stat_id' 

ora_D28_15to19_query = bq.Query(ora_D28_15to19_sql)

ora_D28_15to19_df = ora_D28_15to19_query.execute(output_options = bq.QueryOutput.dataframe()).result()

In [13]:
print(ora_D28_15to19_df.head(20))

                  time  stat_id       sigma_value
0  2018-01-28 15:00:01        6          34488097
1  2018-01-28 15:00:01        7           3622649
2  2018-01-28 15:00:01        8         733360444
3  2018-01-28 15:00:01       19         143524470
4  2018-01-28 15:00:01       20         405485196
5  2018-01-28 15:00:01       22      112017641057
6  2018-01-28 15:00:01       26     3004342915596
7  2018-01-28 15:00:01       55   598644147984384
8  2018-01-28 15:00:01       63    43835569427456
9  2018-01-28 15:00:01       84      251585939467
10 2018-01-28 15:00:01       93  2635036691709952
11 2018-01-28 15:00:01      100      332382354614
12 2018-01-28 15:00:01      194    30702416483744
13 2018-01-28 15:00:01      231      248303313778
14 2018-01-28 15:00:01      623            287506
15 2018-01-28 15:00:01      629         730991281
16 2018-01-28 15:00:01      679                29
17 2018-01-28 15:00:02        6          34488097
18 2018-01-28 15:00:02        7           3622649


# Flatten 시키자

In [14]:
ora_D28_15to19_arr = ora_D28_15to19_df.as_matrix()
print(ora_D28_15to19_arr)
print(ora_D28_15to19_arr.shape)

[[Timestamp('2018-01-28 15:00:01') 6 34488097]
 [Timestamp('2018-01-28 15:00:01') 7 3622649]
 [Timestamp('2018-01-28 15:00:01') 8 733360444]
 ...
 [Timestamp('2018-01-28 19:00:00') 623 287598]
 [Timestamp('2018-01-28 19:00:00') 629 732279238]
 [Timestamp('2018-01-28 19:00:00') 679 22]]
(244800, 3)


## 연습...

In [27]:
temp_arr = []
result_arr = [[]]

temp_arr = [np.append(temp_arr, ora_D28_15to19_arr[0][2])]
temp_arr = [np.append(temp_arr, ora_D28_15to19_arr[1][2])]
temp_arr = [np.append(temp_arr, ora_D28_15to19_arr[2][2])]

print(temp_arr)

result_arr = [np.append(result_arr, temp_arr)]

print(result_arr)
result_arr = np.append(result_arr, temp_arr, axis = 0)
print(result_arr)

[array([7.32530449e+08, 2.24866000e+05, 2.90000000e+01])]
[array([7.32530449e+08, 2.24866000e+05, 2.90000000e+01])]
[[7.32530449e+08 2.24866000e+05 2.90000000e+01]
 [7.32530449e+08 2.24866000e+05 2.90000000e+01]]


In [19]:
print(result_arr)

[7.32530449e+08 2.24866000e+05 2.90000000e+01]


# 진짜..!

In [17]:
result_arr = [[]]

for i in range(14400):
  temp_arr = []
  for j in range(17):
    if(j == 0):
      temp_arr = [np.append(temp_arr, i)]
    temp_arr = [np.append(temp_arr, ora_D28_15to19_arr[17*i+j][2])]
    if(j == 16):
      if(i == 0):
        result_arr = [np.append(result_arr, temp_arr)]
      else:
        result_arr = np.append(result_arr, temp_arr, axis = 0)


In [18]:
print(result_arr)
print(result_arr.shape)

[[0.00000000e+00 3.44880970e+07 3.62264900e+06 ... 2.87506000e+05
  7.30991281e+08 2.90000000e+01]
 [1.00000000e+00 3.44880970e+07 3.62264900e+06 ... 2.87508000e+05
  7.30991617e+08 2.40000000e+01]
 [2.00000000e+00 3.44881080e+07 3.62265000e+06 ... 2.87510000e+05
  7.30992140e+08 2.30000000e+01]
 ...
 [1.43970000e+04 3.45493680e+07 3.63179000e+06 ... 2.87598000e+05
  7.32279236e+08 2.20000000e+01]
 [1.43980000e+04 3.45493680e+07 3.63179100e+06 ... 2.87598000e+05
  7.32279237e+08 2.20000000e+01]
 [1.43990000e+04 3.45493680e+07 3.63179100e+06 ... 2.87598000e+05
  7.32279238e+08 2.20000000e+01]]
(14400, 18)


# Big Query로 보내자

In [20]:
output_df = pd.DataFrame(result_arr)

output_df.columns = ['index', 'stat_value_6', 'stat_value_7', 'stat_value_8', 'stat_value_19', 'stat_value_20', 'stat_value_22', 'stat_value_26', 'stat_value_55', 'stat_value_63', 'stat_value_84', 'stat_value_93', 'stat_value_100', 'stat_value_194', 'stat_value_231', 'stat_value_623', 'stat_value_629', 'stat_value_679']

In [21]:
output_df.to_gbq('z_intern.ora_D18_H_15to19_stat_17s', 'xmdw31', if_exists = 'replace', chunksize = 2000)




Load is 13% Complete
Load is 27% Complete
Load is 41% Complete
Load is 55% Complete
Load is 69% Complete
Load is 83% Complete
Load is 97% Complete
Load is 100% Complete


